name: sonar-cloud-analysis
on:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 4 * * *'
  pull_request_target:
    branches:
      - main
      - dev
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:

  #job for analysing Frontend
  sonarqube-frontend:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Run tests with coverage
        working-directory: apps/frontend
        run: npm test -- --coverage

      - name: SonarQube Scan Frontend
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: apps/frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
          SONAR_SCANNER_OPTS: >
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}

  #job for analysing Backend
  sonarqube-api:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Run tests with coverage
        working-directory: apps/backend
        run: npm test -- --coverage

      - name: SonarQube Scan Backend
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: apps/backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_API }}
          SONAR_SCANNER_OPTS: >
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}

  #job for analysing MobileApp
  sonarqube-mobile:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Run tests with coverage
        working-directory: apps/mobileAppYC
        run: npm test -- --coverage

      - name: SonarQube Scan MobileApp
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: apps/mobileAppYC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_MOBILE }}
          SONAR_SCANNER_OPTS: >
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
